=== javitrujillo99/ProyectosLMSGI/Lenguaje de Marcas/src/Ejercicios/SimulacroExamen.dtd
<!ELEMENT trofeosYGanadores (ganadores+, trofeos?)*>
<!ELEMENT ganadores EMPTY>
<!ELEMENT trofeos (balondeoro, champions, copa, supercopa+)*>
<!ELEMENT balondeoro (#PCDATA)>
<!ELEMENT champions (#PCDATA)>
<!ELEMENT copa (#PCDATA)>
<!ELEMENT supercopa (#PCDATA | jugada)*>
<!ELEMENT jugada EMPTY>
<!ELEMENT noJugada EMPTY>

<!ENTITY % caracteristicas "nombre CDATA #IMPLIED 
							añoNacimiento (1960 | 1961 | 1962 | 1963 | 1964 | 1965) #REQUIRED
							equipo NMTOKENS #IMPLIED
							codigo ID #REQUIRED
							estado NMTOKEN #FIXED 'retirado'">
							
<!ENTITY copa "Copa de España">				

<!ATTLIST ganadores %caracteristicas;>
<!ATTLIST balondeoro codigosRef IDREFS #REQUIRED>
<!ATTLIST champions codigosRef IDREFS #REQUIRED>
<!ATTLIST copa codigoRef IDREF #REQUIRED>
<!ATTLIST supercopa codigosRef IDREFS #REQUIRED>
<!ATTLIST jugada estadio CDATA #REQUIRED>

=== javitrujillo99/ProyectosLMSGI/Lenguaje de Marcas/src/Ejercicios/SimulacroExamen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trofeosYGanadores SYSTEM "SimulacroExamen.dtd">

<trofeosYGanadores>
	<ganadores nombre = "Di Stéfano" añoNacimiento = "1960" equipo = "Real Madrid" codigo = "a" estado = "retirado"/>
	<ganadores nombre = "Koeman" añoNacimiento = "1961" equipo = "Barcelona" codigo = "b" estado = "retirado"/>
	<ganadores nombre = "Pelé" añoNacimiento = "1962" equipo = "Juventus" codigo = "c" estado = "retirado"/>
	<trofeos>
		<balondeoro codigosRef ="a b">Di Stéfano lo ganó 3 veces</balondeoro>
		<champions codigosRef = "a c">Se juega en Wemble</champions>
		<copa codigoRef = "c">Se jugó en el Santiago Bernabéu &copa;</copa>
		<supercopa codigosRef = "a c"><jugada estadio ="Camp Nou"/></supercopa>
		<supercopa codigosRef = "b"/>
		<supercopa codigosRef = "c">El equipo de Pelé la gano en el 1962</supercopa>
	</trofeos>
</trofeosYGanadores>
