=== javitrujillo99/ProyectosLMSGI/Lenguaje de Marcas/src/PrimerExamen/PrimerExamen.dtd
<!ELEMENT articulosDecoracionInterior (articulo*, cliente+, clienteConMasDeUnaCompra*)>
<!ELEMENT articulo (añoFabricacion?, (enStock | noEnStock))*>
<!ELEMENT cliente EMPTY>
<!ELEMENT clienteConMasDeUnaCompra EMPTY>
<!ELEMENT añoFabricacion (#PCDATA)>
<!ELEMENT enStock EMPTY>
<!ELEMENT noEnStock (#PCDATA | fechaStock)*>
<!ELEMENT fechaStock (#PCDATA)>

<!ATTLIST articulo nombre NMTOKENS #REQUIRED 
				   material CDATA #IMPLIED
				   codigoArticulo ID #REQUIRED
				   estado NMTOKEN #FIXED "nuevo">
					
<!ATTLIST enStock cantidad (50|100|150|200) #REQUIRED
				  precioPorUnidad CDATA #IMPLIED>
				  
<!ENTITY % caracteristicas "nombre NMTOKENS #IMPLIED 
							DNI NMTOKEN #REQUIRED
							codigoArticuloComprado IDREF #REQUIRED
							fecha CDATA #IMPLIED">

<!ATTLIST cliente %caracteristicas;>
<!ATTLIST clienteConMasDeUnaCompra nombre NMTOKENS #IMPLIED 
								   DNI NMTOKEN #REQUIRED
								   codigosArticulosComprados IDREFS #REQUIRED
								   fecha CDATA #IMPLIED>
				  		
<!ENTITY noEnStock "Cada 15 días se traen nuevos artículos de este tipo.">

=== javitrujillo99/ProyectosLMSGI/Lenguaje de Marcas/src/PrimerExamen/PrimerExamen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articulosDecoracionInterior SYSTEM "PrimerExamen.dtd">

<articulosDecoracionInterior>
	<articulo nombre = "Jarrón" material = "Cerámica" codigoArticulo = "aph" estado = "nuevo">
		<añoFabricacion>1999</añoFabricacion>
		<enStock cantidad = "50" precioPorUnidad = "50"/>
	</articulo>
	<articulo nombre = "Cuadro" material = "Madera" codigoArticulo = "abc" estado = "nuevo">
		<noEnStock>&noEnStock;</noEnStock>
	</articulo>
	<articulo nombre = "Lámpara" material = "Cristal" codigoArticulo = "jmn" estado = "nuevo">
		<enStock cantidad = "100" precioPorUnidad = "200"/>
	</articulo>
	<articulo nombre = "Florero" material = "Mármol" codigoArticulo = "hgb" estado = "nuevo">
		<noEnStock>
			<fechaStock>Volverá a estar disponible el día 22 de febrero de 2018</fechaStock>
		</noEnStock>
	</articulo>
	<cliente nombre = "Pepe Guijarro" DNI = "23904894E" codigoArticuloComprado = "aph" fecha = "10 de marzo de 2006"/>
	<cliente nombre = "Fran Beato" DNI = "40832981T" codigoArticuloComprado = "jmn" fecha = "23 de Enero de 2010"/>
	<clienteConMasDeUnaCompra nombre = "Carlos Córdoba" DNI = "34989834R" codigosArticulosComprados = "abc hgb" fecha = "22 de Mayo de 2015"/>
</articulosDecoracionInterior>
