=== javitrujillo99/ProyectosLMSGI/Lenguaje de Marcas/src/DTD/Ejercicios/CorreoElectronico.dtd
<!ELEMENT emails (email*)>
<!ELEMENT email (para*, cc*, cco*, asunto, texto, adjunto*)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cco (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT adjunto (nombre, mine-type, longitud)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mine-type (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>

=== javitrujillo99/ProyectosLMSGI/Lenguaje de Marcas/src/DTD/Ejercicios/CorreoElectronico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE emails SYSTEM "CorreoElectronico.dtd">
<emails>
	<email>
		<para>fran@gmail.com</para>
		<cc>carlos@gmail.com</cc>
		<cco>dani@gmail.com</cco>
		<asunto>Eeeeeeeeeeeeeeeeeeeeeee</asunto>
		<texto>Que pasa chavales</texto>
		<adjunto>
			<nombre>Examen.jpg</nombre>
			<mine-type>image/jpeg</mine-type>
			<longitud>894KB</longitud>
		</adjunto>
	</email>
</emails>
